### ISSUE TITLE
oldestTimestamp not advanced, leading to memory pressure

### ISSUE THREAD

**Issue by baiwfg2** [mongodb-partners/mongo-rocks#152]
As I test the latest mongo4.0 rocks implementation,  I find oldestTimestamp seems not to advance, which partly leads to `CleanCommittedKeys` not cleaning any keys. Here's my test setup:

# server
3-nodes replica set, rs.conf() is 
```
rs.initiate({ _id: "rs1", version: 1, members: [ { _id:0,host:"10.108.103.160:50001"},{_id:1,host:"9.34.46.22:50002"},{_id:2,host:"10.108.117.16:50003"}], settings: { chainingAllowed: false} })
```

# YCSB client
Just run the load phase, workload is like:
```
recordcount=100
operationcount=1000
workload=site.ycsb.workloads.CoreWorkload

readallfields=true

readproportion=0
updateproportion=0
scanproportion=0
insertproportion=1

requestdistribution=zipfian

fieldlength=1024
fieldcount=5
mongodb.url=mongodb://10.108.103.160:50001/ycsb?w=1

threadcount=16
table=t
```
And RS is normal, Primary and Secondary all have correct records.
![image](https://user-images.githubusercontent.com/5157680/78979579-bacec500-7b4e-11ea-9090-8eec3836459a.png)

There're two aspects that I suspect oldestTimestamp hasn't advanced:
- From serverStatus
![image](https://user-images.githubusercontent.com/5157680/78979061-a76f2a00-7b4d-11ea-9ffa-e197e3382134.png)

- From gdb breakpoint
Before launching YCSB, I use gdb to attach primary process, and add a breakpoint for `RocksEngine::setOldestTimestamp`. However it doesn't hit.

**Comment by wolfkdy** [comment]
@baiwfg2  thanks for your great finding.
mongoDB4.0 defaults enableMajorityRead = true, in this situation, oldestTimestamp is set by setStableTimestamp, mongo-wt uses stableTimestamp to do inplace-rollback, however mongo-rocks does not do this.
But in mongoRocks' implementaion, setStableTimestamp is left blank, because I thought mongoRocks does not need this. But I forgot in mongo-wt, with enableMajorityRead=true, oldestTs is triggered by setStableTimestamp.

I believe this memory pressue won't happen by setting enableMajorityRead=false. Would you like to continue your test by doing so?

I will fix and test this this weekend.

**Comment by baiwfg2** [comment]
OK. After above fix, YCSB loading is ok. @wolfkdy
![image](https://user-images.githubusercontent.com/5157680/78991272-2888ea00-7b6b-11ea-9b96-11a997bd5a0c.png)
